// Supabase Database type (generated by supabase gen types)
// For now, a minimal stub
export interface Database {
  public: {
    Tables: {
      products: {
        Row: {
          id: string
          name: string
          description: string
          category: string
          source: string
          source_url: string | null
          price: number | null
          cost: number | null
          images: string[]
          specs: Record<string, unknown>
          tags: string[]
          status: string
          risk_level: string
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['products']['Row']>
        Update: Partial<Database['public']['Tables']['products']['Row']>
      }
      // Add other tables as needed
    }
  }
}
